f_read=open('E:\\study\\record.txt')
lines=f_read.readlines()
length=len(lines)
print (length)
#f_muyi_write=open('E:\\study\\muyi1.txt','w')
#f_yang_write=open('E:\\study\\yang1.txt','w')
f_read.close()
